<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>EncorePHP - PHP 5.4 Framework</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	
    <!-- Le styles -->
    <link href="admin/css/bootstrap.min.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
    </style>
    <link href="admin/css/bootstrap-responsive.min.css" rel="stylesheet">
	<link href="admin/css/encorephp.css" rel="stylesheet">
	<script src="admin/js/bootstrap.min.js"></script>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="#">EncorePHP</a>

        </div>
      </div>
    </div>

    <div class="container">

      <!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit">
        <h1>EncorePHP</h1>
        <p>EncorePHP has been successfully installed, pretty easy huh?.</p>
        <p><a class="btn btn-primary btn-large">Learn more &raquo;</a></p>
      </div>

      <!-- Example row of columns -->
      <div class="row">
        <div class="span4">
          <h2>Getting Started</h2>
          <p>Getting started with EncorePHP is easy.
		  In fact this page is being generated by EncorePHP.
		  You can find the controller for this page at 
		  <code>&lt;APP_PATH&gt;/controllers/Index.php</code>
		  and the view at 
		  <code>&lt;APP_PATH&gt;/views/Index.php</code></p>
		  
		  <p>
		  Looking at these pages will be a good place to 
		  get started.</p>
          <p><a class="btn" href="http://docs.encorephp.com/">Documentation &raquo;</a></p>
        </div>
        <div class="span4">
          <h2>Contribute</h2>
          <p>EncorePHP is built by the community, for the community.
		  If you would like to contribute to the development of 
		  EncorePHP then feel free to submit issues and pull requests
		  on our <a href="http://github.com/encorehosts/encorephp">GitHub</a> page.</p>
		  <ul>
			<li><a href="http://github.com/encorehosts/encorephp">Git Repository</a></li>
			<li><a href="http://github.com/encorehosts/encorephp/issues">Issues</a></li>
		  </ul>
       </div>
        <div class="span4">
          <h2>Help</h2>
          <p>Need help with EncorePHP? Why not ask the community? You can post to our <a href="http://forums.encorephp.com/">forums</a> to receive friendly help from our awesome community</p>
          <p><a class="btn" href="http://forums.encorephp.com/">View forums &raquo;</a></p>
        </div>
      </div>

      <hr>

      <footer>
		<p class="pull-right">Page rendered in {rendered_in} using {memory_usage} of memory.</p>
        <p><a href="http://www.encorephp.com/">EncorePHP</a> is released under the MIT license<br><small>v1.0</small></p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>
